WebTriviaPartyGamesTable:
  component: "@serverless/aws-dynamodb"
  inputs:
    name: web-trivia-games
    attributeDefinitions:                    
      - AttributeName: gameId
        AttributeType: S
      # - AttributeName: gameName
      #   AttributeType: S
      # - AttributeName: creator
      #   AttributeType: S
      # Note: The following should be JSON.stringify(Obj)
      # - AttributeName: questions
      #   AttributeType: S
      # - AttributeName: answers
      #   AttributeType: S
      # - AttributeName: categories
      #   AttributeType: S
    keySchema:
      - AttributeName: gameId
        KeyType: HASH

WebTriviaPartyPlaysTable:
  component: "@serverless/aws-dynamodb"
  inputs:
    name: web-trivia-plays
    attributeDefinitions:                    
      - AttributeName: playId
        AttributeType: S
      # - AttributeName: gameId
      #   AttributeType: S
      # - AttributeName: hostSocket
      #   AttributeType: S
    keySchema:
      - AttributeName: playId
        KeyType: HASH
    # globalSecondaryIndexes:
    #   - IndexName: 'gamePlaysIndex'
    #     KeySchema:
    #       - AttributeName: gameId
    #         KeyType: HASH
    #     Projection:
    #       ProjectionType: 'ALL'

WebTriviaPartyPlayClientsTable:
  component: "@serverless/aws-dynamodb"
  inputs:
    name: web-trivia-play-clients
    attributeDefinitions:
      - AttributeName: playId
        AttributeType: S
      - AttributeName: connectionId
        AttributeType: S
      # - AttributeName: nickname
      #   AttributeType: S
    keySchema:
      - AttributeName: playId
        KeyType: HASH
      - AttributeName: connectionId
        KeyType: RANGE
    globalSecondaryIndexes:
      - IndexName: 'connectionIndex'
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        Projection:
          ProjectionType: 'ALL'

WebTriviaPartySocket:
  component: "@serverless/backend-socket"
  inputs:
    name: web-trivia-socket
    description: Socket to handle chats
    memory: 128
    timeout: 10
    env:
      DDB_GAMES_NAME: ${WebTriviaPartyGamesTable.name}
      DDB_PLAYS_NAME: ${WebTriviaPartyPlaysTable.name}
      DDB_PLAY_CLIENTS_NAME: ${WebTriviaPartyPlayClientsTable.name}
    code:
      src: ./backend

WebTriviaPartyApp:
  component: serverless-next.js
  build:
    env:
      WS_SOCKET_URL: ${WebTriviaPartySocket.url}
